version: '3.9'

services:
  gabi:
    image: quay.io/comp-bio-aging/microarrays
    ports:
      - 8787:8787
    environment:
      PASSWORD: "letitbebunu"
    volumes:
      - /data/gabi:/home/rstudio
    labels:
      - "traefik.enable=true"
      # gabi.agingkills.eu
      - "traefik.http.routers.gabi.rule=Host(`gabi.agingkills.eu`)"
      - "traefik.http.routers.gabi.entrypoints=http"
      # gabi.localhost
      - "traefik.http.routers.local_gabi.rule=Host(`gabi.localhost`)"
      - "traefik.http.routers.local_gabi.entrypoints=http"
      #services
      - "traefik.http.services.gabi.loadbalancer.server.port=8787"
    networks:
      - web
    deploy:
      restart_policy:
        condition: any

networks:
  web:
    name: web
    external: true